import type { VastuConfig } from "./admin-store";

const r = (en: string, np: string) => ({ en, np });

export const defaultVastuConfig: VastuConfig = {
  hero: {
    title: "Vastu Shastra Guide",
    subtitle: "Ancient wisdom for modern living — align your home with cosmic energies for harmony, health, and prosperity.",
    bgImage: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=2000&q=80",
    badge: "Tools",
  },
  quickTools: {
    badge: "Quick Tools",
    title: "Vastu Analysis Tools",
    description: "Get instant Vastu guidance for any room or direction.",
    roomToolTitle: "Room-Specific Vastu",
    roomToolDesc: "कोठा-विशेष वास्तु",
    directionToolTitle: "Directional Analysis",
    directionToolDesc: "दिशा विश्लेषण",
  },
  sectionIcons: {
    overview: "🪷",
    elements: "🌍",
    land: "🏞️",
    entrance: "🚪",
    "room-placement": "🏠",
    "kitchen-dining": "🍳",
  },
  sectionKeys: ["overview", "elements", "land", "entrance", "room-placement", "kitchen-dining"],
  sections: {
    overview: {
      title: "Vastu Shastra Overview",
      titleNp: "वास्तु शास्त्र सिंहावलोकन",
      content: [
        r("Vastu Shastra is an ancient Indian science of architecture and building design that dates back thousands of years. The word 'Vastu' means 'dwelling' and 'Shastra' means 'science' or 'knowledge'. It provides guidelines for designing and building structures in harmony with natural laws and cosmic energies.", "वास्तु शास्त्र एक प्राचीन भारतीय वास्तुकला र भवन डिजाइनको विज्ञान हो जुन हजारौं वर्ष पुरानो हो। 'वास्तु' शब्दको अर्थ 'आवास' र 'शास्त्र' को अर्थ 'विज्ञान' वा 'ज्ञान' हो। यसले प्राकृतिक नियम र ब्रह्माण्डीय उर्जाहरूसँग सामञ्जस्यमा संरचनाहरू डिजाइन र निर्माण गर्नका लागि दिशानिर्देशहरू प्रदान गर्दछ।"),
        r("The core principle of Vastu Shastra is that our built environment affects our physical, mental, and spiritual well-being. A Vastu-compliant home or building promotes health, prosperity, happiness, and peace for its inhabitants. Conversely, Vastu defects (Doshas) can lead to various problems in life.", "वास्तु शास्त्रको मूल सिद्धान्त यो हो कि हाम्रो निर्मित वातावरणले हाम्रो शारीरिक, मानसिक र आध्यात्मिक कल्याणलाई असर गर्छ। वास्तु-अनुरूप घर वा भवनले यसका बासिन्दाहरूको लागि स्वास्थ्य, समृद्धि, खुशी र शान्तिलाई बढावा दिन्छ। यसको विपरीत, वास्तु दोषहरूले जीवनमा विभिन्न समस्याहरू निम्त्याउन सक्छ।"),
        r("Vastu is based on five fundamental elements (Panchabhutas): Earth (Prithvi), Water (Jal), Fire (Agni), Air (Vayu), and Space (Akash). These elements are harmonized through proper orientation, proportion, and placement of rooms, doors, windows, and furniture.", "वास्तु पाँच आधारभूत तत्वहरू (पञ्चभूत) मा आधारित छ: पृथ्वी (Earth), जल (Water), अग्नि (Fire), वायु (Air), र आकाश (Space)। यी तत्वहरू कोठा, ढोका, झ्याल र फर्नीचरको उचित अभिमुखीकरण, अनुपात र स्थानको माध्यमबाट सन्तुलित हुन्छन्।"),
      ],
      customTopics: [
        {
          title: "How to Use Vastu in a Modern Home",
          titleNp: "आधुनिक घरमा वास्तु कसरी प्रयोग गर्ने",
          items: [
            r("Start with correct zoning: place quiet, heavy, and private rooms toward South-West; keep light, open, and sacred spaces toward North-East.", "सही जोनिङबाट सुरु गर्नुहोस्: शान्त, भारी र निजी कोठा दक्षिण-पश्चिमतिर; हल्का, खुला र पवित्र ठाउँ उत्तर-पूर्वतिर राख्नुहोस्।"),
            r("Use Vastu as a planning guide alongside structure, climate, natural light, ventilation, and municipal rules.", "वास्तुलाई संरचना, हावापानी, प्राकृतिक प्रकाश, भेन्टिलेसन र नगरपालिकाको नियमसँगै योजना मार्गदर्शनको रूपमा प्रयोग गर्नुहोस्।"),
            r("If a layout is already built, improve energy through cleanliness, lighting, furniture placement, colors, and clutter control.", "लेआउट पहिले नै बनेको छ भने सफाइ, प्रकाश, फर्निचर स्थान, रङ र अव्यवस्था नियन्त्रणबाट उर्जा सुधार गर्नुहोस्।"),
          ],
        },
        {
          title: "Common Vastu Priorities",
          titleNp: "मुख्य वास्तु प्राथमिकता",
          items: [
            r("Main entrance direction, kitchen location, master bedroom location, pooja space, and the center of the house have the highest impact.", "मुख्य ढोका, भान्साको स्थान, मास्टर बेडरूम, पूजा स्थान र घरको केन्द्र सबैभन्दा प्रभावकारी पक्ष हुन्।"),
            r("Do not over-correct minor issues; fix the major conflicts first, especially toilets, heavy loads, fire, and water placement.", "साना कुरा धेरै सच्याउन नलाग्नुहोस्; पहिले शौचालय, भारी भार, आगो र पानीको स्थान जस्ता ठूला द्वन्द्व समाधान गर्नुहोस्।"),
          ],
        },
      ],
    },
    elements: {
      title: "Five Elements & Principles",
      titleNp: "पाँच तत्व र सिद्धान्त",
      content: [
        r("The five elements (Panchabhutas) form the foundation of Vastu Shastra. Each element governs specific directions and aspects of life, and must be balanced in any built structure.", "पाँच तत्वहरू (पञ्चभूत) वास्तु शास्त्रको जग हो। प्रत्येक तत्वले विशिष्ट दिशा र जीवनका पक्षहरूको शासन गर्दछ, र कुनै पनि निर्मित संरचनामा सन्तुलित हुनुपर्छ।"),
        r("Earth (Prithvi - South-West): Represents stability, patience, and endurance. The heaviest and most solid elements of the house should be in the South-West direction. Master bedroom, heavy furniture, and storage are ideal in this zone.", "पृथ्वी (Prithvi - दक्षिण-पश्चिम): स्थिरता, धैर्य र सहनशीलताको प्रतिनिधित्व गर्दछ। घरको सबैभन्दा भारी र ठोस तत्वहरू दक्षिण-पश्चिम दिशामा हुनुपर्छ। मास्टर बेडरूम, भारी फर्नीचर र भण्डारण यस क्षेत्रको लागि आदर्श हो।"),
        r("Water (Jal - North-East): Represents flow, purity, and prosperity. Water elements like tanks, wells, and fountains should be in the North-East direction. This area must be kept open, clean, and clutter-free.", "जल (Jal - उत्तर-पूर्व): प्रवाह, शुद्धता र समृद्धिको प्रतिनिधित्व गर्दछ। ट्याङ्की, इनार र फाउन्टेन जस्ता पानी तत्वहरू उत्तर-पूर्व दिशामा हुनुपर्छ। यस क्षेत्रलाई खुला, सफा र अव्यवस्थित-मुक्त राख्नुपर्छ।"),
        r("Fire (Agni - South-East): Represents energy, transformation, and vitality. The kitchen should be in the South-East direction. Electrical appliances and the cooking stove are best placed in this zone.", "अग्नि (Agni - दक्षिण-पूर्व): उर्जा, परिवर्तन र जीवनशक्तिको प्रतिनिधित्व गर्दछ। भान्सा दक्षिण-पूर्व दिशामा हुनुपर्छ। विद्युतीय उपकरण र चुल्हो यस क्षेत्रमा राख्नु उत्तम हुन्छ।"),
        r("Air (Vayu - North-West): Represents movement, communication, and freshness. Guest rooms, children's rooms, and parking areas are ideal in the North-West direction. This zone should be light and airy.", "वायु (Vayu - उत्तर-पश्चिम): आवागमन, सञ्चार र ताजगीको प्रतिनिधित्व गर्दछ। पाहुना कोठा, बच्चाको कोठा र पार्किङ क्षेत्र उत्तर-पश्चिम दिशामा आदर्श हो। यो क्षेत्र हल्का र हावादार हुनुपर्छ।"),
        r("Space (Akash - Center/Brahmasthan): Represents the cosmic void and spiritual energy. The center of the house (Brahmasthan) must be kept open and free of any construction, pillars, or heavy objects. This allows positive cosmic energy to flow freely throughout the home.", "आकाश (Akash - केन्द्र/ब्रह्मस्थान): ब्रह्माण्डीय शून्यता र आध्यात्मिक उर्जाको प्रतिनिधित्व गर्दछ। घरको केन्द्र (ब्रह्मस्थान) खुला र कुनै पनि निर्माण, स्तम्भ वा भारी वस्तुहरूबाट मुक्त राख्नुपर्छ। यसले सकारात्मक ब्रह्माण्डीय उर्जा घरभरि स्वतन्त्र रूपमा प्रवाह गर्न अनुमति दिन्छ।"),
      ],
      customTopics: [
        {
          title: "Element Placement Checklist",
          titleNp: "तत्व स्थान जाँचसूची",
          items: [
            r("Water: place tanks, fountains, drinking water, or meditation openness toward North or North-East where possible.", "जल: सम्भव भए पानी ट्याङ्की, फाउन्टेन, पिउने पानी वा ध्यानको खुलापन उत्तर वा उत्तर-पूर्वतिर राख्नुहोस्।"),
            r("Fire: place stove, oven, inverter, and major electrical appliances toward South-East.", "अग्नि: चुल्हो, ओभन, इन्भर्टर र प्रमुख विद्युतीय उपकरण दक्षिण-पूर्वतिर राख्नुहोस्।"),
            r("Earth: place heavy furniture, safes, wardrobes, and master bedroom functions toward South-West.", "पृथ्वी: भारी फर्निचर, सेफ, दराज र मास्टर बेडरूमका कार्य दक्षिण-पश्चिमतिर राख्नुहोस्।"),
            r("Air: keep North-West light, ventilated, and suitable for movement-based spaces like guest room or parking.", "वायु: उत्तर-पश्चिमलाई हल्का, हावादार र पाहुना कोठा वा पार्किङ जस्ता आवागमनयुक्त ठाउँका लागि उपयुक्त राख्नुहोस्।"),
          ],
        },
        {
          title: "Balancing Tips",
          titleNp: "सन्तुलन सुझाव",
          items: [
            r("Balance does not mean equal quantity; it means each element is placed where its energy works naturally.", "सन्तुलनको अर्थ बराबर मात्रा होइन; प्रत्येक तत्वलाई उसको उर्जा स्वाभाविक रूपमा काम गर्ने ठाउँमा राख्नु हो।"),
            r("Avoid mixing direct fire and water, such as stove and sink touching each other.", "चुल्हो र सिंक सँगै टाँसिने जस्ता आगो र पानीको प्रत्यक्ष मिश्रणबाट बच्नुहोस्।"),
          ],
        },
      ],
    },
    land: {
      title: "Land Selection & Preparation",
      titleNp: "जग्गा चयन र तयारी",
      content: [
        r("Choosing the right plot of land is the first and most crucial step in Vastu-compliant construction. The shape, size, slope, and surroundings of the land all affect the Vastu energy of the building.", "सही जग्गाको छनोट वास्तु-अनुरूप निर्माणको पहिलो र सबैभन्दा महत्त्वपूर्ण कदम हो। जग्गाको आकार, नाप, ढलान र वरपरको वातावरण सबैले भवनको वास्तु उर्जालाई असर गर्छ।"),
        r("Ideal Plot Shapes: Square and rectangular plots are considered most auspicious. Plots with North or East sides longer than South or West sides are favorable. Irregular shapes like L-shaped or triangular plots should be corrected with Vastu remedies.", "आदर्श प्लट आकार: वर्ग र आयताकार प्लटहरू सबैभन्दा शुभ मानिन्छन्। दक्षिण वा पश्चिम भन्दा उत्तर वा पूर्व तर्फ लामो भएको प्लटहरू अनुकूल हुन्छन्। एल-आकार वा त्रिकोणीय प्लट जस्ता अनियमित आकारहरू वास्तु उपचारले सच्याउनुपर्छ।"),
        r("Land Slope: The land should slope toward the North, East, or Northeast direction. Slope toward South or West is considered inauspicious as it can lead to financial and health problems.", "जग्गाको ढलान: जग्गा उत्तर, पूर्व वा उत्तर-पूर्व दिशातिर ढल्कनुपर्छ। दक्षिण वा पश्चिमतिरको ढलान अशुभ मानिन्छ किनकि यसले आर्थिक र स्वास्थ्य समस्याहरू निम्त्याउन सक्छ।"),
        r("Soil Quality: The soil should be fertile and well-draining.", "माटोको गुणस्तर: माटो उर्वर र राम्रो निकास भएको हुनुपर्छ।"),
        r("Surroundings: Avoid plots near cemeteries, hospitals, temples (directly opposite), electrical substations, or sewage treatment plants. Plots with roads on the North or East side are favorable.", "वरपरको वातावरण: श्मशान घाट, अस्पताल, मन्दिर (सीधा विपरीत), विद्युत उपकेन्द्र वा ढल प्रशोधन प्लान्ट नजिकको प्लटहरूबाट बच्नुहोस्। उत्तर वा पूर्व तर्फ सडक भएको प्लटहरू अनुकूल हुन्छन्।"),
      ],
      customTopics: [
        {
          title: "Before Buying Land",
          titleNp: "जग्गा किन्नु अघि",
          items: [
            r("Check road approach, plot shape, slope, drainage, soil stability, sunlight, and neighboring structures before finalizing.", "अन्तिम गर्नु अघि बाटो, जग्गाको आकार, ढलान, निकास, माटोको स्थिरता, घाम र छिमेकी संरचना जाँच गर्नुहोस्।"),
            r("Prefer plots with open North or East sides, proper drainage, and no major obstruction directly in front of the entrance side.", "उत्तर वा पूर्वतिर खुला, राम्रो निकास भएको र प्रवेशतर्फ सीधा ठूलो अवरोध नभएको जग्गा प्राथमिकता दिनुहोस्।"),
            r("Confirm legal access, setback, by-laws, and buildable area; Vastu planning should fit real construction permissions.", "कानुनी पहुँच, सेटब्याक, नियम र निर्माणयोग्य क्षेत्र पुष्टि गर्नुहोस्; वास्तु योजना वास्तविक निर्माण अनुमतिसँग मिल्नुपर्छ।"),
          ],
        },
        {
          title: "Plot Correction Ideas",
          titleNp: "प्लट सुधार उपाय",
          items: [
            r("Irregular plots can often be corrected through compound wall alignment, landscape buffers, or functional zoning.", "अनियमित प्लटलाई कम्पाउन्ड वाल मिलान, ल्याण्डस्केप बफर वा कार्यात्मक जोनिङबाट धेरै हदसम्म सुधार गर्न सकिन्छ।"),
            r("If the South-West is low or open, make it heavier through landscape, storage, or built mass where structurally possible.", "दक्षिण-पश्चिम होचो वा खुला छ भने संरचनागत रूपमा सम्भव ठाउँमा ल्याण्डस्केप, भण्डारण वा भवन भारबाट भारी बनाउनुहोस्।"),
          ],
        },
      ],
    },
    entrance: {
      title: "Doors & Main Entrance",
      titleNp: "ढोका र मुख्य प्रवेशद्वार",
      content: [
        r("The main entrance (Main Door) is the most important element of a Vastu-compliant home. It is the gateway for cosmic energy (Prana) to enter the house. The design, direction, size, and placement of the main door significantly impact the residents' lives.", "मुख्य प्रवेशद्वार (मुख्य ढोका) वास्तु-अनुरूप घरको सबैभन्दा महत्तपूर्ण तत्व हो। यो ब्रह्माण्डीय उर्जा (प्राण) घरमा प्रवेश गर्ने ढोका हो। मुख्य ढोकाको डिजाइन, दिशा, आकार र स्थानले बासिन्दाहरूको जीवनमा महत्त्वपूर्ण प्रभाव पार्दछ।"),
        r("Best Entrance Directions: North and East are the most auspicious directions for the main entrance. Northeast is also considered highly favorable.", "उत्तम प्रवेश दिशाहरू: उत्तर र पूर्व मुख्य प्रवेशद्वारको लागि सबैभन्दा शुभ दिशाहरू हुन्। उत्तर-पूर्व पनि अत्यन्त अनुकूल मानिन्छ।"),
        r("Door Specifications: The main door should be the largest door in the house, made of solid wood. It should have two doors (double-leaf door) opening inward. Auspicious symbols like Swastika, Om, or footprints of Goddess Lakshmi should be carved or placed on the door.", "ढोका विशिष्टताहरू: मुख्य ढोका घरको सबैभन्दा ठूलो ढोका हुनुपर्छ, ठोस काठले बनेको। यसका दुई ढोका (डबल-लीफ ढोका) भित्रतिर खोलिने हुनुपर्छ। स्वस्तिक, ॐ वा देवी लक्ष्मीको पाइला जस्ता शुभ प्रतीकहरू ढोकामा कुँदिएको वा राखिएको हुनुपर्छ।"),
        r("Additional Doors: Windows and doors in the Northeast should be larger than those in the Southwest. The number of doors and windows should be even.", "अतिरिक्त ढोकाहरू: उत्तर-पूर्वमा झ्याल र ढोकाहरू दक्षिण-पश्चिम भन्दा ठूला हुनुपर्छ। ढोका र झ्यालहरूको संख्या जोर हुनुपर्छ।"),
      ],
      customTopics: [
        {
          title: "Main Door Planning",
          titleNp: "मुख्य ढोका योजना",
          items: [
            r("Keep the entrance bright, clean, easy to identify, and slightly more prominent than internal doors.", "प्रवेशद्वार उज्यालो, सफा, सजिलै चिनिने र भित्री ढोकाभन्दा अलि प्रमुख राख्नुहोस्।"),
            r("Avoid direct alignment from the main door to toilet doors, back doors, or sharp corners.", "मुख्य ढोकाबाट शौचालय ढोका, पछाडिको ढोका वा तीखा कुनातिर सिधा लाइन नबनाउनुहोस्।"),
            r("Use a solid threshold, good lighting, and a clutter-free foyer to slow and settle incoming energy.", "आउँदो उर्जा स्थिर बनाउन बलियो थ्रेसहोल्ड, राम्रो प्रकाश र अव्यवस्था रहित फोयर प्रयोग गर्नुहोस्।"),
          ],
        },
        {
          title: "Entrance Corrections",
          titleNp: "प्रवेश सुधार",
          items: [
            r("For less favorable entrance directions, improve lighting, cleanliness, door quality, nameplate placement, and entry landscaping.", "कम अनुकूल दिशाका ढोकामा प्रकाश, सफाइ, ढोकाको गुणस्तर, नेमप्लेट र प्रवेश ल्याण्डस्केप सुधार गर्नुहोस्।"),
            r("Place shoes, bins, and broken objects away from the main door zone.", "जुत्ता, फोहोर डब्बा र टुटेका वस्तु मुख्य ढोकाको क्षेत्रबाट टाढा राख्नुहोस्।"),
          ],
        },
      ],
    },
    "room-placement": {
      title: "Room Placement Guide",
      titleNp: "कोठा स्थान गाइड",
      content: [
        r("The placement of rooms within a house is critical to Vastu harmony. Each room serves a specific purpose and must be located in the appropriate direction to maximize its benefits.", "घर भित्र कोठाहरूको स्थान वास्तु सद्भावको लागि महत्त्वपूर्ण छ। प्रत्येक कोठाले एक विशिष्ट उद्देश्य प्रदान गर्दछ र यसको लाभहरू अधिकतम बनाउन उपयुक्त दिशामा स्थित हुनुपर्छ।"),
        r("Center (Brahmasthan): Keep completely open and free of rooms, pillars, walls, and heavy objects.", "केन्द्र (ब्रह्मस्थान): पूर्ण रूपमा खुला र कोठा, स्तम्भ, पर्खाल र भारी वस्तुहरूबाट मुक्त राख्नुहोस्।"),
        r("Master Bedroom: South-West corner is ideal. This provides stability and strength to the head of the family.", "मास्टर बेडरूम: दक्षिण-पश्चिम कुना आदर्श हो। यसले परिवारको मुखियालाई स्थिरता र शक्ति प्रदान गर्दछ।"),
        r("Children's Bedroom: West or North-West is best for children as it fosters creativity and growth.", "बच्चाको शयनकक्ष: पश्चिम वा उत्तर-पश्चिम बच्चाहरूको लागि उत्तम हो किनकि यसले सृजनशीलता र वृद्धिलाई बढावा दिन्छ।"),
        r("Kitchen: South-East corner (Agni zone). The person cooking should face East.", "भान्सा: दक्षिण-पूर्व कुना (अग्नि क्षेत्र)। पकाउने व्यक्ति पूर्वतिर फर्कनुपर्छ।"),
        r("Pooja Room: North-East corner (Ishan). The most sacred space in the home.", "पूजा कोठा: उत्तर-पूर्व कुना (ईशान)। घरको सबैभन्दा पवित्र स्थान।"),
        r("Living Room: North, East, or North-East. Should be spacious with maximum openings toward North and East.", "बस्ने कोठा: उत्तर, पूर्व वा उत्तर-पूर्व। उत्तर र पूर्वतिर अधिकतम खुल्ला ठाउँको साथ फराकिलो हुनुपर्छ।"),
        r("Dining Room: Near the kitchen, preferably in the West or North-West.", "खाना कक्ष: भान्साको नजिक, अधिमानतः पश्चिम वा उत्तर-पश्चिममा।"),
        r("Bathroom & Toilet: West, North-West, or South-East (only for bathrooms, not toilets).", "स्नानघर र शौचालय: पश्चिम, उत्तर-पश्चिम वा दक्षिण-पूर्व (स्नानघरको लागि मात्र, शौचालयको लागि होइन)।"),
        r("Staircase: South, West, or South-West of the house. Staircase should not be in the center or North-East.", "सीढी: घरको दक्षिण, पश्चिम वा दक्षिण-पश्चिम। सीढी केन्द्र वा उत्तर-पूर्वमा हुनु हुँदैन।"),
      ],
      customTopics: [
        {
          title: "Planning Sequence",
          titleNp: "योजना क्रम",
          items: [
            r("First fix the center, entrance, kitchen, master bedroom, toilets, and staircase; then arrange secondary rooms.", "पहिले केन्द्र, प्रवेश, भान्सा, मास्टर बेडरूम, शौचालय र सिँढी मिलाउनुहोस्; त्यसपछि सहायक कोठा मिलाउनुहोस्।"),
            r("Keep public spaces closer to the entrance and private spaces deeper inside the plan.", "सार्वजनिक ठाउँ प्रवेश नजिक र निजी ठाउँ योजना भित्र गहिरो भागमा राख्नुहोस्।"),
            r("Use furniture weight to support Vastu zones: heavier storage South/West, lighter seating North/East.", "फर्निचरको भारबाट वास्तु जोनलाई समर्थन गर्नुहोस्: भारी भण्डारण दक्षिण/पश्चिम, हल्का बसाइ उत्तर/पूर्व।"),
          ],
        },
        {
          title: "Apartment & Small Plot Guidance",
          titleNp: "अपार्टमेन्ट र सानो प्लट मार्गदर्शन",
          items: [
            r("When exact placement is impossible, prioritize direction of use: sleeping head, cooking face, study face, and prayer face.", "ठ्याक्कै स्थान सम्भव नभए प्रयोगको दिशा प्राथमिकता दिनुहोस्: सुत्ने टाउको, पकाउने मुख, पढ्ने मुख र पूजा मुख।"),
            r("Avoid placing heavy storage in North-East and avoid keeping the center congested.", "उत्तर-पूर्वमा भारी भण्डारण नराख्नुहोस् र केन्द्रलाई भिडभाडयुक्त नबनाउनुहोस्।"),
          ],
        },
      ],
    },
    "kitchen-dining": {
      title: "Kitchen & Dining",
      titleNp: "भान्सा र खाना कक्ष",
      content: [
        r("KITCHEN PLACEMENT: Ideal: Southeast (fire element). Alternative: Northwest. Cook should face East. AVOID Northeast.", "भान्सा राख्ने ठाउँ: आदर्श: दक्षिण-पूर्व (आगो तत्व)। विकल्प: उत्तर-पश्चिम। पकाउनेले पूर्वतिर मुख गरेर पकाउनुपर्छ। उत्तर-पूर्वबाट टाढा रहनुहोस्।"),
        r("KITCHEN SPECIFICS: Sink with tap water should be in Northeast of kitchen. Sink should not be near the stove.", "भान्साको विशेषताहरू: नलको पानीको सिंक भान्साको उत्तर-पूर्वमा हुनुपर्छ। सिंक चुल्होको नजिक हुनु हुँदैन।"),
        r("DINING ROOM: Should be near the kitchen in Southeast, Northwest, or Northeast. West side encourages profitability.", "खाना कक्ष: दक्षिण-पूर्व, उत्तर-पश्चिम वा उत्तर-पूर्वमा भान्साको नजिक हुनुपर्छ। पश्चिम तिरले लाभलाई प्रोत्साहन गर्दछ।"),
        r("SEATING ARRANGEMENT: The head of the family should face East during meals. Others can face East, West, or North — never South.", "बस्ने व्यवस्था: परिवारको मुखियाले खाना खाँदा पूर्वतिर मुख गर्नुपर्छ। अरूले पूर्व, पश्चिम वा उत्तरतिर मुख गर्न सक्छन् — कहिल्यै दक्षिणतिर नगर्नुहोस्।"),
        r("COLORS: Recommended colors for dining area: light blue, yellow, saffron, and light green.", "रङहरू: खाना क्षेत्रको लागि सिफारिस गरिएका रङहरू: हल्का निलो, पहेंलो, केसरी र हल्का हरियो।"),
      ],
      customTopics: [
        {
          title: "Kitchen Work Triangle",
          titleNp: "भान्साको कार्य त्रिकोण",
          items: [
            r("Keep stove, sink, and refrigerator convenient but separated enough to avoid fire-water conflict.", "चुल्हो, सिंक र फ्रिजलाई सुविधाजनक तर आगो-पानी द्वन्द्व नहुने गरी पर्याप्त दूरीमा राख्नुहोस्।"),
            r("Use the South and West sides for tall units, storage, and heavier appliances.", "अग्ला युनिट, भण्डारण र भारी उपकरणका लागि दक्षिण र पश्चिम भाग प्रयोग गर्नुहोस्।"),
            r("Keep the North-East of the kitchen light, clean, and suitable for water or washing where possible.", "भान्साको उत्तर-पूर्व भाग हल्का, सफा र सम्भव भए पानी वा धुने कामका लागि उपयुक्त राख्नुहोस्।"),
          ],
        },
        {
          title: "Dining Experience",
          titleNp: "खाना खाने वातावरण",
          items: [
            r("Dining should feel warm, settled, and connected to the kitchen without exposing waste or clutter.", "खाना क्षेत्र न्यानो, स्थिर र भान्सासँग जोडिएको हुनुपर्छ तर फोहोर वा अव्यवस्था देखिने गरी होइन।"),
            r("Use balanced lighting and calm wall colors to support family conversation and digestion.", "पारिवारिक संवाद र पाचनलाई सहयोग गर्न सन्तुलित प्रकाश र शान्त भित्ते रङ प्रयोग गर्नुहोस्।"),
          ],
        },
      ],
    },
  },
  rooms: {
    "living-room": {
      idealDirection: r("North, East, or Northeast directions. The living room should be at the front of the house, spacious and large.", "उत्तर (North), पूर्व (East) वा उत्तर-पूर्व (Northeast) दिशाहरू। बस्ने कोठा घरको अगाडि, चौडा र ठूलो हुनुपर्छ।"),
      facingDirection: r("Face North or East while sitting. Facing North or East promotes positive thinking and creativity.", "उत्तर (North) वा पूर्व (East) तिर मुख गरेर बस्नुहोस्। उत्तर वा पूर्वतिर मुख गरेर बस्दा मानिसहरूले अधिक सकारात्मक सोच र सृजनशीलता प्राप्त गर्छन्।"),
      tips: [
        r("Keep Northeast corner light and open", "उत्तर-पूर्व कुनालाई हल्का र खुला राख्नुहोस्"),
        r("Use bright and welcoming colors", "उज्यालो र स्वागत योग्य रङहरू प्रयोग गर्नुहोस्"),
        r("Place heavy furniture in Southwest", "भारी फर्नीचर दक्षिण-पश्चिममा राख्नुहोस्"),
        r("Ensure good natural light", "राम्रो प्राकृतिक प्रकाश सुनिश्चित गर्नुहोस्"),
        r("Keep green and healthy plants in living room", "बस्ने कोठामा हरियो र स्वस्थ बोटबिरुवाहरू राख्नुहोस्"),
        r("Keep center part of living room empty", "बस्ने कोठाको केन्द्र भागलाई खाली राख्नुहोस्"),
        r("Place positive pictures in living room", "बस्ने कोठामा सकारात्मक चित्रहरू राख्नुहोस्"),
      ],
      avoid: [
        r("Avoid living room in Southwest", "दक्षिण-पश्चिममा बस्ने कोठा नराख्नुहोस्"),
        r("No toilets adjacent to living room", "बस्ने कोठा संगै शौचालय नबनाउनुहोस्"),
        r("Don't place TV in Northeast", "उत्तर-पूर्वमा टिभी नराख्नुहोस्"),
        r("Avoid dark colors in Northeast", "उत्तर-पूर्वमा गाढा रङहरू प्रयोग नगर्नुहोस्"),
        r("Avoid keeping broken objects in living room", "बस्ने कोठामा कुनै पनि प्रकारको टुटेका वस्तुहरू नराख्नुहोस्"),
        r("Avoid living room door opening directly to toilet", "बस्ने कोठाको ढोका सिधै शौचालयमा नखुल्ने गरी बनाउनुहोस्"),
        r("Avoid too much clutter in living room", "बस्ने कोठामा धेरै झोल वा अनावश्यक सामान नराख्नुहोस्"),
      ],
    },
    "master-bedroom": {
      idealDirection: r("Southwest direction is ideal for the master bedroom. This placement promotes stability, strength, and a strong bond between couples.", "दक्षिण-पश्चिम (Southwest) दिशा मास्टर बेडरूमको लागि आदर्श हो। यो स्थानले स्थिरता, शक्ति र दम्पतीबीच बलियो सम्बन्धलाई बढावा दिन्छ।"),
      facingDirection: r("Sleep with your head toward South or East. Sleeping with the head toward South promotes restful sleep and good health.", "दक्षिण (South) वा पूर्व (East) तिर टाउको राखेर सुत्नुहोस्। दक्षिणतिर टाउको राखेर सुत्दा राम्रो निद्रा र स्वास्थ्यलाई बढावा दिन्छ।"),
      tips: [
        r("Place bed in Southwest corner of room", "ओछ्यान कोठाको दक्षिण-पश्चिम कुनामा राख्नुहोस्"),
        r("Use soft, calming colors like light pink or cream", "हल्का गुलाबी वा क्रिम जस्ता नरम, शान्त रङहरू प्रयोग गर्नुहोस्"),
        r("Keep Northeast part of bedroom clean and light", "शयनकक्षको उत्तर-पूर्व भाग सफा र उज्यालो राख्नुहोस्"),
        r("Place wardrobe in North or West wall", "अलमारी उत्तर वा पश्चिम पर्खालमा राख्नुहोस्"),
        r("Ensure proper ventilation and fresh air", "उचित भेन्टिलेसन र ताजा हावा सुनिश्चित गर्नुहोस्"),
        r("Keep electronic devices away from bed", "इलेक्ट्रोनिक उपकरणहरू ओछ्यानबाट टाढा राख्नुहोस्"),
      ],
      avoid: [
        r("No bedroom in Northeast or Southeast", "उत्तर-पूर्व वा दक्षिण-पूर्वमा शयनकक्ष नराख्नुहोस्"),
        r("Avoid mirrors facing the bed", "ओछ्यानतिर फर्केको ऐना नराख्नुहोस्"),
        r("No toilet attached to pooja room wall", "पूजा कोठाको पर्खालमा शौचालय नजोड्नुहोस्"),
        r("Avoid TV or computer in bedroom", "शयनकक्षमा टिभी वा कम्प्युटर नराख्नुहोस्"),
        r("Don't sleep with head toward North", "उत्तरतिर टाउको राखेर नसुत्नुहोस्"),
        r("Avoid dark and heavy colors in bedroom", "शयनकक्षमा गाढा र भारी रङहरू प्रयोग नगर्नुहोस्"),
      ],
    },
    "kids-bedroom": {
      idealDirection: r("West, Northwest, or North direction. Children's bedrooms in West or Northwest foster creativity, learning, and overall development.", "पश्चिम (West), उत्तर-पश्चिम (Northwest) वा उत्तर (North) दिशा। पश्चिम वा उत्तर-पश्चिममा बच्चाको कोठा राख्दा सृजनशीलता, सिकाइ र समग्र विकासलाई बढावा मिल्छ।"),
      facingDirection: r("Face East or North while studying. Facing East improves concentration, memory retention, and academic performance.", "पढ्दा पूर्व (East) वा उत्तर (North) तिर मुख गर्नुहोस्। पूर्वतिर मुख गरेर पढ्दा बच्चाको एकाग्रता, स्मरण शक्ति र शैक्षिक प्रदर्शनमा सुधार हुन्छ।"),
      tips: [
        r("Place study desk in East or North of room", "अध्ययन डेस्क कोठाको पूर्व वा उत्तरमा राख्नुहोस्"),
        r("Use bright, vibrant colors for walls", "भित्ताका लागि उज्यालो, जीवन्त रङहरू प्रयोग गर्नुहोस्"),
        r("Keep room well-ventilated with natural light", "प्राकृतिक प्रकाशको साथ कोठा राम्रोसँग हावा चल्ने बनाउनुहोस्"),
        r("Place bed along South or West wall", "ओछ्यान दक्षिण वा पश्चिम पर्खालमा राख्नुहोस्"),
        r("Store toys in North or West direction", "खेलौनाहरू उत्तर वा पश्चिम दिशामा राख्नुहोस्"),
      ],
      avoid: [
        r("No bedroom in Southwest for children", "दक्षिण-पश्चिममा बच्चाको कोठा नराख्नुहोस्"),
        r("Avoid placing bed under a beam", "ओछ्यान मुनि बीम नराख्नुहोस्"),
        r("Don't place study desk against South wall", "दक्षिण पर्खालमा अध्ययन डेस्क नराख्नुहोस्"),
        r("Avoid electronic gadgets near sleeping area", "सुत्ने क्षेत्र नजिक इलेक्ट्रोनिक उपकरणहरू नराख्नुहोस्"),
      ],
    },
    kitchen: {
      idealDirection: r("Southeast direction (Agni / Fire element) is ideal for the kitchen. Alternative: Northwest direction is also acceptable.", "दक्षिण-पूर्व (Southeast) दिशा भान्साको लागि आदर्श हो। विकल्प: उत्तर-पश्चिम दिशा पनि स्वीकार्य छ।"),
      facingDirection: r("Cook facing East. The person cooking should face East, which is considered auspicious.", "पकाउनेले पूर्व (East) तिर मुख गरेर पकाउनुपर्छ। पकाउने व्यक्तिले पूर्वतिर मुख गर्नुपर्छ, जुन शुभ मानिन्छ।"),
      tips: [
        r("Place cooking stove in Southeast of kitchen", "चुल्हो भान्साको दक्षिण-पूर्वमा राख्नुहोस्"),
        r("Sink should be in Northeast direction", "सिंक उत्तर-पूर्व दिशामा हुनुपर्छ"),
        r("Keep a gap between sink and stove", "सिंक र चुल्होबीचको दूरी राख्नुहोस्"),
        r("Storage shelves in South and West walls", "भण्डारण शेल्फ दक्षिण र पश्चिम पर्खालमा राख्नुहोस्"),
        r("Use light and warm color schemes", "हल्का र न्यानो रङ योजनाहरू प्रयोग गर्नुहोस्"),
        r("Ensure exhaust fan or chimney in Southeast", "दक्षिण-पूर्वमा एक्जस्ट फ्यान वा चिम्नी राख्नुहोस्"),
      ],
      avoid: [
        r("Never place kitchen in Northeast", "उत्तर-पूर्वमा भान्सा कहिल्यै नराख्नुहोस्"),
        r("No kitchen under staircase", "सिँढी मुनि भान्सा नराख्नुहोस्"),
        r("Stove and sink not adjacent (fire vs water conflict)", "चुल्हो र सिंक एकअर्काको छेउमा नराख्नुहोस्"),
        r("Avoid toilet above or adjacent to kitchen", "भान्साको माथि वा छेउमा शौचालय नबनाउनुहोस्"),
        r("Don't keep kitchen dirty or cluttered", "भान्सा फोहोर वा अव्यवस्थित नराख्नुहोस्"),
        r("Avoid dark colors in kitchen", "भान्सामा गाढा रङहरू प्रयोग नगर्नुहोस्"),
      ],
    },
    "dining-room": {
      idealDirection: r("Near kitchen in Southeast, Northwest, or Northeast. The dining room should be adjacent to the kitchen for convenience.", "दक्षिण-पूर्व, उत्तर-पश्चिम, वा उत्तर-पूर्वमा भान्साको नजिक। खाना कक्ष सुविधाको लागि भान्साको नजिक हुनुपर्छ।"),
      facingDirection: r("Head of family faces East during meals. Others can face East, West, or North. Never face South while eating.", "परिवारको मुखियाले खाना खाँदा पूर्वतिर मुख गर्नुपर्छ। अरूले पूर्व, पश्चिम, वा उत्तरतिर मुख गर्न सक्छन्। खाँदा कहिल्यै दक्षिणतिर नगर्नुहोस्।"),
      tips: [
        r("Use square or rectangular dining table (no round/oval)", "वर्ग वा आयताकार खाना टेबल प्रयोग गर्नुहोस् (गोलो/अण्डाकार होइन)"),
        r("Water/wash basin in East or North", "पानी/धुने कुण्ड पूर्व वा उत्तरमा राख्नुहोस्"),
        r("Use light blue, yellow, saffron, light green colors", "हल्का निलो, पहेंलो, केसरी, हल्का हरियो रङहरू प्रयोग गर्नुहोस्"),
        r("Hang family photos on South or West wall", "पारिवारिक फोटोहरू दक्षिण वा पश्चिम पर्खालमा झुण्ड्याउनुहोस्"),
        r("Keep dining area well-lit and ventilated", "खाना कक्ष राम्रोसँग उज्यालो र हावा चल्ने राख्नुहोस्"),
      ],
      avoid: [
        r("Don't place dining table against Southwest wall", "दक्षिण-पश्चिम पर्खालमा खाना टेबल नराख्नुहोस्"),
        r("No dining room attached to toilet", "शौचालयसँग जोडिएको खाना कक्ष नराख्नुहोस्"),
        r("Never face South while eating", "खाँदा कहिल्यै दक्षिणतिर नगर्नुहोस्"),
        r("No water basin in Southeast or Southwest", "दक्षिण-पूर्व वा दक्षिण-पश्चिममा पानीको कुण्ड नराख्नुहोस्"),
        r("Avoid kitchen waste bin visible from dining", "भान्साको फोहोर खाना कक्षबाट देखिने नराख्नुहोस्"),
      ],
    },
    "pooja-room": {
      idealDirection: r("Northeast corner (Ishan) is the most sacred direction for the pooja room. It promotes peace, prosperity, and spiritual growth.", "उत्तर-पूर्व कुना (ईशान) पूजा कोठाको लागि सबैभन्दा पवित्र दिशा हो। यसले शान्ति, समृद्धि र आध्यात्मिक वृद्धिलाई बढावा दिन्छ।"),
      facingDirection: r("Face East or North while praying. The worshipper should face East or North toward the deities.", "पूजा गर्दा पूर्व (East) वा उत्तर (North) तिर मुख गर्नुहोस्। पूजा गर्नेले पूर्व वा उत्तरतिर मुख गर्नुपर्छ।"),
      tips: [
        r("Keep pooja room in Northeast corner of house", "पूजा कोठा घरको उत्तर-पूर्व कुनामा राख्नुहोस्"),
        r("Keep clean, well-lit, and properly ventilated", "सफा, उज्यालो र राम्रो हावा चल्ने राख्नुहोस्"),
        r("Use wooden platform for idols (not marble/stone)", "मूर्तिहरूको लागि काठको प्लेटफर्म प्रयोग गर्नुहोस्"),
        r("Place idols facing West so devotee faces East", "पूर्वतिर फर्केर पूजा गर्न मूर्तिहरू पश्चिमतिर राख्नुहोस्"),
        r("Use brass or copper lamps for lighting", "प्रकाशको लागि पित्तल वा तामाको दिया प्रयोग गर्नुहोस्"),
      ],
      avoid: [
        r("No pooja room under staircase", "सिँढी मुनि पूजा कोठा नराख्नुहोस्"),
        r("No toilet adjacent or above pooja room", "पूजा कोठाको छेउमा वा माथि शौचालय नबनाउनुहोस्"),
        r("No bathroom attached to pooja room", "पूजा कोठामा स्नानघर नजोड्नुहोस्"),
        r("Avoid sleeping or non-spiritual activities in pooja room", "पूजा कोठामा सुत्ने वा गैर-आध्यात्मिक गतिविधिहरू नगर्नुहोस्"),
        r("Don't place idols directly on floor", "मूर्तिहरू भुइँमा सीधा नराख्नुहोस्"),
      ],
    },
    bathroom: {
      idealDirection: r("West or Northwest direction. Bathrooms and toilets in the West or Northwest direction are considered suitable.", "पश्चिम (West) वा उत्तर-पश्चिम (Northwest) दिशा। पश्चिम वा उत्तर-पश्चिम दिशामा शौचालय र बाथरूम उपयुक्त मानिन्छ।"),
      facingDirection: r("Face North-South while using the toilet. The ideal alignment is North-South direction.", "शौचालय प्रयोग गर्दा उत्तर-दक्षिण तिर फर्कनुहोस्। आदर्श पङ्क्ति उत्तर-दक्षिण दिशा हो।"),
      tips: [
        r("Place bathroom in West or Northwest", "पश्चिम वा उत्तर-पश्चिममा बाथरूम राख्नुहोस्"),
        r("Ensure exhaust fan for ventilation", "भेन्टिलेसनको लागि एक्जस्ट फ्यान राख्नुहोस्"),
        r("Keep bathroom clean and dry at all times", "बाथरूम सधैं सफा र सुख्खा राख्नुहोस्"),
        r("Use light-colored tiles (white, cream, light blue)", "हल्का रङका टाइल्स प्रयोग गर्नुहोस्"),
        r("Keep door closed when not in use", "प्रयोगमा नहुँदा ढोका बन्द राख्नुहोस्"),
      ],
      avoid: [
        r("No toilet in Northeast (Ishan) corner", "उत्तर-पूर्व (ईशान) कुनामा शौचालय नबनाउनुहोस्"),
        r("Avoid toilet in Southeast (fire zone)", "दक्षिण-पूर्व (आगो क्षेत्र) मा शौचालय नबनाउनुहोस्"),
        r("No toilet adjacent to pooja room", "पूजा कोठाको छेउमा शौचालय नबनाउनुहोस्"),
        r("Don't attach bathroom to kitchen wall", "भान्साको पर्खालमा बाथरूम नजोड्नुहोस्"),
        r("Avoid toilet in center of house (Brahmasthan)", "घरको केन्द्र (ब्रह्मस्थान) मा शौचालय नबनाउनुहोस्"),
      ],
    },
    "study-room": {
      idealDirection: r("East, North, or Northeast direction. These directions enhance concentration, memory, and intellectual capabilities.", "पूर्व (East), उत्तर (North) वा उत्तर-पूर्व (Northeast) दिशा। यी दिशाहरूले एकाग्रता, स्मरण शक्ति र बौद्धिक क्षमताहरू बढाउँछन्।"),
      facingDirection: r("Face East or North while studying. Facing East improves memory retention and concentration.", "पढ्दा पूर्व (East) वा उत्तर (North) तिर मुख गर्नुहोस्। पूर्वतिर मुख गरेर पढ्दा स्मरण शक्ति र एकाग्रतामा सुधार हुन्छ।"),
      tips: [
        r("Place study desk in East or North of room", "अध्ययन डेस्क कोठाको पूर्व वा उत्तरमा राख्नुहोस्"),
        r("Keep room clutter-free and organized", "कोठा अव्यवस्थित-मुक्त र व्यवस्थित राख्नुहोस्"),
        r("Use light green or light blue wall colors", "हल्का हरियो वा हल्का निलो पर्खाल रङहरू प्रयोग गर्नुहोस्"),
        r("Ensure adequate natural light from East windows", "पूर्वी झ्यालहरूबाट पर्याप्त प्राकृतिक प्रकाश सुनिश्चित गर्नुहोस्"),
        r("Place bookshelves on South or West walls", "पुस्तक शेल्फहरू दक्षिण वा पश्चिम पर्खालमा राख्नुहोस्"),
      ],
      avoid: [
        r("No study room in Southwest or South", "दक्षिण-पश्चिम वा दक्षिणमा अध्ययन कोठा नराख्नुहोस्"),
        r("Don't study facing South or West", "दक्षिण वा पश्चिमतिर फर्केर नपढ्नुहोस्"),
        r("Avoid sleeping in study room", "अध्ययन कोठामा नसुत्नुहोस्"),
        r("No electronic distractions near study area", "अध्ययन क्षेत्रमा इलेक्ट्रोनिक विचलनहरू नराख्नुहोस्"),
      ],
    },
    "guest-room": {
      idealDirection: r("Northwest direction is ideal for the guest room. The Northwest is ruled by the Air element, which is welcoming and provides comfort to guests.", "उत्तर-पश्चिम (Northwest) दिशा पाहुना कोठाको लागि आदर्श हो। उत्तर-पश्चिम वायु तत्व (Vayu) द्वारा शासित छ, जसले पाहुनाहरूलाई स्वागत र आराम प्रदान गर्दछ।"),
      facingDirection: r("No specific facing requirement, but bed should be placed along South or West wall for stability.", "कुनै विशेष अनुहार आवश्यकता छैन, तर स्थिरताको लागि ओछ्यान दक्षिण वा पश्चिम पर्खालमा राख्नुपर्छ।"),
      tips: [
        r("Place guest room in Northwest direction", "पाहुना कोठा उत्तर-पश्चिम दिशामा राख्नुहोस्"),
        r("Keep room welcoming with warm colors", "न्यानो रङहरूले कोठालाई स्वागतयोग्य राख्नुहोस्"),
        r("Provide attached bathroom in West", "पश्चिममा संलग्न बाथरूम प्रदान गर्नुहोस्"),
        r("Ensure good ventilation and natural light", "राम्रो भेन्टिलेसन र प्राकृतिक प्रकाश सुनिश्चित गर्नुहोस्"),
      ],
      avoid: [
        r("Avoid guest room in Southwest (reserved for owner)", "दक्षिण-पश्चिममा पाहुना कोठा नराख्नुहोस् (मालिकको लागि आरक्षित)"),
        r("No guest room in Northeast (sacred zone)", "उत्तर-पूर्वमा पाहुना कोठा नराख्नुहोस् (पवित्र क्षेत्र)"),
        r("Don't attach guest room toilet to pooja room wall", "पूजा कोठाको पर्खालमा पाहुना कोठाको शौचालय नजोड्नुहोस्"),
      ],
    },
    "store-room": {
      idealDirection: r("South or West direction. The store room should be in the South or West part of the house. These directions are ideal for storage and preservation.", "दक्षिण (South) वा पश्चिम (West) दिशा। भण्डार कोठा घरको दक्षिण वा पश्चिम भागमा हुनुपर्छ। यी दिशाहरू भण्डारण र संरक्षणको लागि आदर्श हो।"),
      facingDirection: r("No specific facing requirement for store room.", "भण्डार कोठाको लागि कुनै विशेष अनुहार आवश्यकता छैन।"),
      tips: [
        r("Place heavy items on South and West sides", "भारी वस्तुहरू दक्षिण र पश्चिम तर्फ राख्नुहोस्"),
        r("Keep store room organized and clean", "भण्डार कोठा व्यवस्थित र सफा राख्नुहोस्"),
        r("Ensure proper ventilation to prevent moisture", "नमी रोक्नको लागि उचित भेन्टिलेसन सुनिश्चित गर्नुहोस्"),
        r("Use shelves on South and West walls", "दक्षिण र पश्चिम पर्खालहरूमा शेल्फहरू प्रयोग गर्नुहोस्"),
      ],
      avoid: [
        r("No store room in Northeast", "उत्तर-पूर्वमा भण्डार कोठा नराख्नुहोस्"),
        r("Avoid store room near main entrance", "मुख्य ढोका नजिक भण्डार कोठा नराख्नुहोस्"),
        r("Don't use store room as living or sleeping space", "भण्डार कोठालाई बस्ने वा सुत्ने ठाउँको रूपमा प्रयोग नगर्नुहोस्"),
      ],
    },
  },
  directions: {
    north: {
      deity: "Kubera (God of Wealth)",
      element: "Water",
      description: r("North direction is governed by Kubera, the God of Wealth. This direction brings abundance, success, and career advancement when properly utilized.", "उत्तर दिशा कुबेर (धनका देवता) द्वारा शासित छ। यो दिशा आर्थिक वृद्धि र समृद्धिको लागि अत्यन्त शुभ छ।"),
      recommended: [
        r("Main entrance in North is highly auspicious", "उत्तरमा मुख्य ढोका अत्यन्त शुभ छ"),
        r("Best for living room and study room", "बस्ने कोठा र अध्ययन कोठाको लागि उत्तम"),
        r("Ideal for water elements (fountains, tanks)", "पानी तत्वहरूको लागि आदर्श (फाउन्टेन, ट्याङ्की)"),
        r("Keep this area open and clutter-free", "यस क्षेत्रलाई खुला र अव्यवस्थित-मुक्त राख्नुहोस्"),
        r("Good for placing heavy items in Northwest of this zone", "यस क्षेत्रको उत्तर-पश्चिममा भारी वस्तुहरू राख्नुहोस्"),
      ],
      avoid: [
        r("No heavy structures blocking North side", "उत्तर तर्फ भारी संरचनाहरू नराख्नुहोस्"),
        r("No toilet or bathroom in North zone", "उत्तर क्षेत्रमा शौचालय वा स्नानघर नबनाउनुहोस्"),
        r("Avoid dark and heavy colors", "गाढा र भारी रङहरू प्रयोग नगर्नुहोस्"),
        r("No bedroom in North direction", "उत्तर दिशामा शयनकक्ष नराख्नुहोस्"),
        r("Avoid kitchen in North zone", "उत्तर क्षेत्रमा भान्सा नराख्नुहोस्"),
      ],
    },
    northeast: {
      deity: "Ishana (Lord Shiva)",
      element: "Water & Space",
      description: r("Northeast (Ishan) is the most sacred direction in Vastu Shastra. This direction is the source of all positive cosmic energy.", "उत्तर-पूर्व (ईशान) वास्तु शास्त्रको सबैभन्दा पवित्र दिशा हो। यो दिशा सबै सकारात्मक ब्रह्माण्डीय उर्जाको स्रोत हो।"),
      recommended: [
        r("Best location for pooja room and meditation", "पूजा कोठा र ध्यानको लागि उत्तम स्थान"),
        r("Ideal for underground water tanks and wells", "भूमिगत पानी ट्याङ्की र इनारहरूको लागि आदर्श"),
        r("Keep this corner open with maximum openings", "यस कुनालाई अधिकतम खुल्ला ठाउँसहित खुला राख्नुहोस्"),
        r("Use light colors and natural materials", "हल्का रङ र प्राकृतिक सामग्रीहरू प्रयोग गर्नुहोस्"),
        r("Best for garden, open space, and courtyard", "बगैंचा, खुला ठाउँ र आँगनको लागि उत्तम"),
      ],
      avoid: [
        r("No toilet or bathroom ever in Northeast", "उत्तर-पूर्वमा कहिल्यै शौचालय वा स्नानघर नबनाउनुहोस्"),
        r("No kitchen in Northeast", "उत्तर-पूर्वमा भान्सा नराख्नुहोस्"),
        r("No bedroom or master bedroom", "शयनकक्ष वा मास्टर बेडरूम नराख्नुहोस्"),
        r("No heavy structures or storage", "भारी संरचना वा भण्डारण नराख्नुहोस्"),
        r("Avoid septic tanks, garbage, or dirty items", "सेप्टिक ट्याङ्की, फोहोर वा फोहोर वस्तुहरू नराख्नुहोस्"),
      ],
    },
    east: {
      deity: "Indra (King of Gods)",
      element: "Sun / Fire",
      description: r("East direction is ruled by Indra, the King of Gods, and is associated with the rising Sun. This direction brings vitality, health, and prosperity.", "पूर्व दिशा इन्द्र (देवताहरूको राजा) द्वारा शासित छ र उदाउँदो सूर्यसँग सम्बन्धित छ। यो दिशाले जीवनशक्ति, स्वास्थ्य र समृद्धि ल्याउँछ।"),
      recommended: [
        r("Main entrance in East is very auspicious", "पूर्वमा मुख्य ढोका धेरै शुभ छ"),
        r("Best for windows and openings for morning sunlight", "बिहानको सूर्यको प्रकाशको लागि झ्यालहरूको लागि उत्तम"),
        r("Ideal for living room and study room", "बस्ने कोठा र अध्ययन कोठाको लागि आदर्श"),
        r("Best for open verandas and balconies", "खुला बरामदा र बालकनीहरूको लागि उत्तम"),
        r("Keep this side with more open space", "यस तर्फ अधिक खुला ठाउँ राख्नुहोस्"),
      ],
      avoid: [
        r("No bedroom in East", "पूर्वमा शयनकक्ष नराख्नुहोस्"),
        r("No toilet in East direction", "पूर्व दिशामा शौचालय नबनाउनुहोस्"),
        r("Avoid blocking East with tall structures", "अग्लो संरचनाहरूले पूर्व नछोप्नुहोस्"),
        r("No heavy storage in East", "पूर्वमा भारी भण्डारण नराख्नुहोस्"),
        r("Avoid dark or heavy walls on East side", "पूर्व तर्फ गाढा वा भारी पर्खालहरू नराख्नुहोस्"),
      ],
    },
    southeast: {
      deity: "Agni (God of Fire)",
      element: "Fire (Agni)",
      description: r("Southeast direction is governed by Agni, the God of Fire. This direction is the zone of the Fire element and is therefore the most suitable location for the kitchen.", "दक्षिण-पूर्व दिशा अग्नि (आगोका देवता) द्वारा शासित छ। यो दिशा आगो तत्वको क्षेत्र हो र त्यसैले भान्साको लागि सबैभन्दा उपयुक्त स्थान हो।"),
      recommended: [
        r("Ideal location for kitchen (Agni zone)", "भान्साको लागि आदर्श स्थान (अग्नि क्षेत्र)"),
        r("Best for electrical appliances and equipment", "विद्युतीय उपकरणहरूको लागि उत्तम"),
        r("Place cooking stove in Southeast", "चुल्हो दक्षिण-पूर्वमा राख्नुहोस्"),
        r("Use warm colors like red, orange, pink", "रातो, सुन्तला, गुलाबी जस्ता न्यानो रङहरू प्रयोग गर्नुहोस्"),
        r("Good for placing electrical panels and meters", "विद्युतीय प्यानल र मिटरहरूको लागि राम्रो"),
      ],
      avoid: [
        r("No bedroom or master bedroom", "शयनकक्ष वा मास्टर बेडरूम नराख्नुहोस्"),
        r("No toilet or bathroom in Southeast", "दक्षिण-पूर्वमा शौचालय वा स्नानघर नबनाउनुहोस्"),
        r("Avoid water elements (sink, tank) in this zone", "यस क्षेत्रमा पानी तत्वहरू नराख्नुहोस्"),
        r("No pooja room in Southeast", "दक्षिण-पूर्वमा पूजा कोठा नराख्नुहोस्"),
        r("Avoid main entrance in Southeast", "दक्षिण-पूर्वमा मुख्य ढोका नबनाउनुहोस्"),
      ],
    },
    south: {
      deity: "Yama (God of Death)",
      element: "Earth",
      description: r("South direction is governed by Yama, the God of death. It provides stability and protection when properly balanced. Heavy items and storage are best placed in the South.", "दक्षिण दिशा यम (मृत्युका देवता) द्वारा शासित छ। यसले स्थिरता र सुरक्षा प्रदान गर्दछ जब सही तरिकाले संतुलित हुन्छ।"),
      recommended: [
        r("Best for master bedroom placement", "मास्टर बेडरूम राख्नको लागि उत्तम"),
        r("Ideal for heavy furniture and storage", "भारी फर्नीचर र स्टोरेजको लागि आदर्श"),
        r("Good for staircase and structural support", "सीढी र संरचनात्मक समर्थनको लागि राम्रो"),
        r("Use warm colors like red, orange, brown", "रातो, सुन्तला, खैरो जस्ता तातो रङहरू प्रयोग गर्नुहोस्"),
        r("Keep safe and valuables in this direction", "यस दिशामा तिजोरी र मूल्यवान वस्तुहरू राख्नुहोस्"),
      ],
      avoid: [
        r("Avoid main entrance in south", "दक्षिणमा मुख्य ढोका नबनाउनुहोस्"),
        r("No water elements or bathrooms in south", "दक्षिण दिशामा पानीका तत्व वा शौचालय नबनाउनुहोस्"),
        r("Don't keep this area empty", "यस क्षेत्रलाई खाली नराख्नुहोस्"),
        r("Avoid light colors in this zone", "यस जोनमा हल्का रङहरू प्रयोग नगर्नुहोस्"),
        r("Avoid underground tanks or water sources", "भूमिगत ट्याङ्की वा पानीको स्रोत नबनाउनुहोस्"),
      ],
    },
    southwest: {
      deity: "Nirriti (Goddess of Destruction)",
      element: "Earth",
      description: r("Southwest direction is extremely important for stability and strength. The heaviest and most elevated parts of the house should be in the Southwest.", "दक्षिण-पश्चिम दिशा स्थिरता र शक्तिको लागि अत्यन्त महत्त्वपूर्ण छ। घरको सबैभन्दा भारी र अग्लो भाग दक्षिण-पश्चिममा हुनुपर्छ।"),
      recommended: [
        r("Ideal for master bedroom (owner's room)", "मास्टर बेडरूमको लागि आदर्श (मालिकको कोठा)"),
        r("Best for heavy storage and almirahs", "भारी भण्डारण र अलमारीहरूको लागि उत्तम"),
        r("Make this side higher and heavier", "यस तर्फ अग्लो र भारी बनाउनुहोस्"),
        r("Best for valuables and safe placement", "मूल्यवान वस्तु र सुरक्षित स्थानको लागि उत्तम"),
        r("Use dark and earthy colors", "गाढा र माटोको रङहरू प्रयोग गर्नुहोस्"),
      ],
      avoid: [
        r("No kitchen in Southwest", "दक्षिण-पश्चिममा भान्सा नराख्नुहोस्"),
        r("No toilet or bathroom in Southwest", "दक्षिण-पश्चिममा शौचालय वा स्नानघर नबनाउनुहोस्"),
        r("No main entrance in Southwest", "दक्षिण-पश्चिममा मुख्य ढोका नबनाउनुहोस्"),
        r("Avoid water elements (fountains, tanks)", "पानी तत्वहरू नराख्नुहोस्"),
        r("Don't keep this area open or empty", "यस क्षेत्रलाई खुला वा खाली नराख्नुहोस्"),
      ],
    },
    west: {
      deity: "Varuna (God of Water)",
      element: "Water",
      description: r("West direction is governed by Varuna, the God of Water. This direction is associated with prosperity, fame, and social recognition.", "पश्चिम दिशा वरुण (पानीका देवता) द्वारा शासित छ। यो दिशा समृद्धि, प्रसिद्धि र सामाजिक मान्यतासँग सम्बन्धित छ।"),
      recommended: [
        r("Good for dining room and children's bedrooms", "खाना कक्ष र बच्चाको शयनकक्षको लागि राम्रो"),
        r("Ideal for store room and storage", "भण्डार कोठा र भण्डारणको लागि आदर्श"),
        r("Best for toilets and bathrooms", "शौचालय र स्नानघरको लागि उत्तम"),
        r("Suitable for staircase placement", "सीढी राख्नको लागि उपयुक्त"),
        r("Keep this side moderately built", "यस तर्फ मध्यम रूपमा निर्मित राख्नुहोस्"),
      ],
      avoid: [
        r("No main entrance in West", "पश्चिममा मुख्य ढोका नबनाउनुहोस्"),
        r("Avoid kitchen in West direction", "पश्चिम दिशामा भान्सा नराख्नुहोस्"),
        r("No pooja room in West", "पश्चिममा पूजा कोठा नराख्नुहोस्"),
        r("Avoid underground water tanks in West", "पश्चिममा भूमिगत पानी ट्याङ्की नराख्नुहोस्"),
      ],
    },
    northwest: {
      deity: "Vayu (God of Air)",
      element: "Air (Vayu)",
      description: r("Northwest direction is governed by Vayu, the God of Air. This direction represents movement, communication, and social connections.", "उत्तर-पश्चिम दिशा वायु (हावाका देवता) द्वारा शासित छ। यो दिशाले आवागमन, सञ्चार र सामाजिक सम्बन्धहरूको प्रतिनिधित्व गर्दछ।"),
      recommended: [
        r("Ideal for guest room and children's bedroom", "पाहुना कोठा र बच्चाको शयनकक्षको लागि आदर्श"),
        r("Best for vehicle parking and garage", "सवारी पार्किङ र ग्यारेजको लागि उत्तम"),
        r("Good for toilet and bathroom placement", "शौचालय र स्नानघर राख्नको लागि राम्रो"),
        r("Suitable for secondary kitchen", "माध्यमिक भान्साको लागि उपयुक्त"),
        r("Keep this area lightweight and airy", "यस क्षेत्रलाई हल्का र हावादार राख्नुहोस्"),
      ],
      avoid: [
        r("No master bedroom in Northwest", "उत्तर-पश्चिममा मास्टर बेडरूम नराख्नुहोस्"),
        r("No main entrance in Northwest", "उत्तर-पश्चिममा मुख्य ढोका नबनाउनुहोस्"),
        r("Avoid heavy structures in Northwest", "उत्तर-पश्चिममा भारी संरचनाहरू नराख्नुहोस्"),
        r("No pooja room in Northwest", "उत्तर-पश्चिममा पूजा कोठा नराख्नुहोस्"),
        r("Avoid underground storage or heavy items", "भूमिगत भण्डारण वा भारी वस्तुहरू नराख्नुहोस्"),
      ],
    },
  },
  roomOptions: [
    { id: "living-room", label: "Living Room", labelNp: "बस्ने कोठा" },
    { id: "master-bedroom", label: "Master Bedroom", labelNp: "मास्टर बेडरूम" },
    { id: "kids-bedroom", label: "Children's Bedroom", labelNp: "बच्चाको कोठा" },
    { id: "kitchen", label: "Kitchen", labelNp: "भान्सा" },
    { id: "dining-room", label: "Dining Room", labelNp: "खाना कक्ष" },
    { id: "pooja-room", label: "Pooja Room", labelNp: "पूजा कोठा" },
    { id: "bathroom", label: "Bathroom & Toilet", labelNp: "शौचालय" },
    { id: "study-room", label: "Study / Home Office", labelNp: "अध्ययन कोठा" },
    { id: "guest-room", label: "Guest Room", labelNp: "पाहुना कोठा" },
    { id: "store-room", label: "Store Room", labelNp: "भण्डार कोठा" },
  ],
  directionOptions: [
    { id: "north", label: "North (उत्तर)", subtitle: "Wealth & Prosperity" },
    { id: "northeast", label: "Northeast (उत्तर-पूर्व)", subtitle: "Spirituality & Peace" },
    { id: "east", label: "East (पूर्व)", subtitle: "Health & Vitality" },
    { id: "southeast", label: "Southeast (दक्षिण-पूर्व)", subtitle: "Energy & Transformation" },
    { id: "south", label: "South (दक्षिण)", subtitle: "Stability & Protection" },
    { id: "southwest", label: "Southwest (दक्षिण-पश्चिम)", subtitle: "Strength & Foundation" },
    { id: "west", label: "West (पश्चिम)", subtitle: "Prosperity & Fame" },
    { id: "northwest", label: "Northwest (उत्तर-पश्चिम)", subtitle: "Movement & Communication" },
  ],
};
