export interface ProjectData {
  slug: string;
  title: string;
  file: string;
  location: string;
  completion: string;
  images: string[];
  description: string;
  materials: { name: string; desc: string }[];
  costEstimation: { item: string; amount: string }[];
  specs: { label: string; value: string }[];
}

export const projects: ProjectData[] = [
  {
    slug: "bridge-frame",
    title: "Bridge Frame",
    file: "brigfe.glb",
    location: "Butwal, Nepal",
    completion: "December 2025",
    images: [
      "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800&q=80",
      "https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?w=800&q=80",
    ],
    description: "A steel-and-concrete bridge frame structure designed for pedestrian and light vehicular traffic across a 30-metre span. The design emphasises minimal material usage while maintaining high load-bearing capacity.",
    materials: [
      { name: "Reinforced Concrete", desc: "Grade M25 for foundations and abutments" },
      { name: "Structural Steel", desc: "ISMB 300 beams with corrosion-resistant coating" },
      { name: "Precast Deck Panels", desc: "Lightweight precast concrete panels for rapid installation" },
      { name: "Galvanised Railings", desc: "Hot-dip galvanised steel handrails and guardrails" },
    ],
    costEstimation: [
      { item: "Foundation & Abutments", amount: "NPR 12,00,000" },
      { item: "Steel Superstructure", amount: "NPR 28,00,000" },
      { item: "Deck Panels & Paving", amount: "NPR 8,50,000" },
      { item: "Railings & Safety", amount: "NPR 3,20,000" },
      { item: "Labour & Installation", amount: "NPR 9,00,000" },
      { item: "Miscellaneous", amount: "NPR 4,30,000" },
    ],
    specs: [
      { label: "Total Span", value: "30 m" },
      { label: "Width", value: "4.5 m" },
      { label: "Load Capacity", value: "20 tonnes" },
      { label: "Design Life", value: "50 years" },
      { label: "Seismic Zone", value: "Zone V compliant" },
    ],
  },
  {
    slug: "first-sample",
    title: "First Sample Villa",
    file: "firstsample.glb",
    location: "Pokhara, Nepal",
    completion: "March 2026",
    images: [
      "https://images.unsplash.com/photo-1600585153490-76fb20a32601?w=800&q=80",
      "https://images.unsplash.com/photo-1618220179428-22790b461013?w=800&q=80",
    ],
    description: "A modern 3-bedroom villa serving as a sample prototype for a larger housing development. Features open-plan living, large glazing for natural light, and a green roof for thermal efficiency.",
    materials: [
      { name: "Fly-ash Bricks", desc: "Eco-friendly bricks for all external walls" },
      { name: "Double-Glazed Windows", desc: "UPVC frames with 5mm+12mm+5mm glass" },
      { name: "Concrete Roof Tiles", desc: "Mangalore pattern tiles for sloped roof" },
      { name: "Vitrified Flooring", desc: "800x800mm vitrified tiles in living areas" },
      { name: "Low-VOC Paint", desc: "Water-based interior paint for healthy indoor air" },
    ],
    costEstimation: [
      { item: "Site Preparation", amount: "NPR 3,50,000" },
      { item: "Foundation & Structure", amount: "NPR 18,00,000" },
      { item: "Roofing", amount: "NPR 5,50,000" },
      { item: "Windows & Doors", amount: "NPR 4,20,000" },
      { item: "Flooring & Finishes", amount: "NPR 7,80,000" },
      { item: "Plumbing & Electrical", amount: "NPR 6,00,000" },
      { item: "Labour", amount: "NPR 10,00,000" },
    ],
    specs: [
      { label: "Total Area", value: "1,850 sq.ft" },
      { label: "Bedrooms", value: "3" },
      { label: "Bathrooms", value: "3" },
      { label: "Floors", value: "2" },
      { label: "Parking", value: "1 car" },
      { label: "Energy Rating", value: "4-star" },
    ],
  },
  {
    slug: "folding-structure",
    title: "Folding Roof Pavilion",
    file: "folding.glb",
    location: "Kathmandu, Nepal",
    completion: "August 2025",
    images: [
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&q=80",
      "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800&q=80",
    ],
    description: "An innovative folding roof structure for an outdoor events pavilion. The kinetic roof system allows the space to transform from open-air to fully enclosed in minutes.",
    materials: [
      { name: "Aluminium Frame", desc: "Lightweight 6061-T6 aluminium alloy sections" },
      { name: "Polycarbonate Panels", desc: "Multi-wall UV-protected polycarbonate glazing" },
      { name: "Stainless Steel Hinges", desc: "316-grade marine stainless steel for all pivot points" },
      { name: "Hydraulic Actuators", desc: "Electric linear actuators for automated folding" },
      { name: "PTFE Membrane", desc: "Tensile fabric roof sections for weather protection" },
    ],
    costEstimation: [
      { item: "Foundation & Base", amount: "NPR 15,00,000" },
      { item: "Aluminium Frame", amount: "NPR 22,00,000" },
      { item: "Roof Panels & Membrane", amount: "NPR 18,00,000" },
      { item: "Hydraulic System", amount: "NPR 8,50,000" },
      { item: "Electrical & Controls", amount: "NPR 5,00,000" },
      { item: "Installation & Commissioning", amount: "NPR 11,50,000" },
    ],
    specs: [
      { label: "Covered Area", value: "350 sq.m" },
      { label: "Max Height", value: "12 m" },
      { label: "Open/Close Time", value: "90 seconds" },
      { label: "Wind Resistance", value: "120 km/h" },
      { label: "Capacity", value: "400 people" },
    ],
  },
  {
    slug: "house-model",
    title: "Modern Family Home",
    file: "house.glb",
    location: "Lalitpur, Nepal",
    completion: "January 2026",
    images: [
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&q=80",
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&q=80",
    ],
    description: "A contemporary 4-bedroom family home designed for multi-generational living. The layout includes a ground-floor bedroom for elderly access, open kitchen-dining, and a rooftop garden.",
    materials: [
      { name: "Autoclaved Aerated Concrete Blocks", desc: "AAC blocks for thermal insulation" },
      { name: "Stone Cladding", desc: "Local schist stone for exterior feature walls" },
      { name: "Engineered Wood Flooring", desc: "Oak-engineered planks for bedrooms" },
      { name: "Solar Tiles", desc: "Integrated photovoltaic roof tiles" },
      { name: "Rainwater Harvesting System", desc: "10,000-litre underground storage tank" },
    ],
    costEstimation: [
      { item: "Land Development", amount: "NPR 8,00,000" },
      { item: "Foundation & Structure", amount: "NPR 24,00,000" },
      { item: "Roof & Solar Integration", amount: "NPR 9,50,000" },
      { item: "Finishes & Flooring", amount: "NPR 12,00,000" },
      { item: "Kitchen & Wardrobes", amount: "NPR 6,50,000" },
      { item: "Plumbing, Electrical & HVAC", amount: "NPR 10,00,000" },
      { item: "Landscaping & Boundary", amount: "NPR 5,00,000" },
    ],
    specs: [
      { label: "Total Area", value: "2,800 sq.ft" },
      { label: "Bedrooms", value: "4" },
      { label: "Bathrooms", value: "4" },
      { label: "Floors", value: "G+1" },
      { label: "Parking", value: "2 cars" },
      { label: "Solar Capacity", value: "3.2 kW" },
    ],
  },
  {
    slug: "mailbox",
    title: "Mailbox Cottage",
    file: "mailbox.glb",
    location: "Bandipur, Nepal",
    completion: "June 2025",
    images: [
      "https://images.unsplash.com/photo-1540541338287-41700207dee6?w=800&q=80",
      "https://images.unsplash.com/photo-1618220179428-22790b461013?w=800&q=80",
    ],
    description: "A charming countryside cottage designed as a weekend retreat. The compact footprint maximises space efficiency with a fold-out loft bedroom and integrated storage solutions.",
    materials: [
      { name: "Stone Masonry", desc: "Local river stone for load-bearing walls" },
      { name: "Timber Frame Roof", desc: "Sal wood trusses with clay tile roofing" },
      { name: "Lime Plaster", desc: "Breathable lime-based interior plaster" },
      { name: "Recycled Wood Flooring", desc: "Reclaimed timber floorboards" },
    ],
    costEstimation: [
      { item: "Foundation & Masonry", amount: "NPR 6,50,000" },
      { item: "Roof Structure & Tiles", amount: "NPR 4,00,000" },
      { item: "Windows & Doors", amount: "NPR 2,50,000" },
      { item: "Interior Finishes", amount: "NPR 3,80,000" },
      { item: "Plumbing & Electrical", amount: "NPR 2,20,000" },
      { item: "Furniture & Fit-Out", amount: "NPR 3,00,000" },
    ],
    specs: [
      { label: "Total Area", value: "850 sq.ft" },
      { label: "Bedrooms", value: "2" },
      { label: "Bathrooms", value: "1" },
      { label: "Floors", value: "G+LOFT" },
      { label: "Plot Size", value: "0.5 acres" },
    ],
  },
  {
    slug: "sand-terrain",
    title: "Sandstone Retreat",
    file: "sand.glb",
    location: "Chitwan, Nepal",
    completion: "October 2025",
    images: [
      "https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?w=800&q=80",
      "https://images.unsplash.com/photo-1600585153490-76fb20a32601?w=800&q=80",
    ],
    description: "A desert-modern retreat built on sandy terrain near Chitwan National Park. The design uses rammed earth walls for natural cooling and large overhangs for shade.",
    materials: [
      { name: "Rammed Earth", desc: "Stabilised rammed earth walls for thermal mass" },
      { name: "Bamboo Ceilings", desc: "Treated bamboo mat panels for ceiling finishes" },
      { name: "Terracotta Flooring", desc: "Handmade terracotta tiles throughout" },
      { name: "Thatched Roof", desc: "Traditional Nepali thatch over modern insulation layer" },
    ],
    costEstimation: [
      { item: "Site Preparation", amount: "NPR 4,00,000" },
      { item: "Rammed Earth Walls", amount: "NPR 12,00,000" },
      { item: "Roof & Insulation", amount: "NPR 6,50,000" },
      { item: "Flooring & Finishes", amount: "NPR 5,00,000" },
      { item: "Plumbing & Off-Grid Systems", amount: "NPR 7,50,000" },
      { item: "Landscaping", amount: "NPR 4,00,000" },
    ],
    specs: [
      { label: "Total Area", value: "1,600 sq.ft" },
      { label: "Bedrooms", value: "3" },
      { label: "Bathrooms", value: "2" },
      { label: "Floors", value: "1" },
      { label: "Off-Grid", value: "Solar + Rainwater" },
    ],
  },
  {
    slug: "stop-sign",
    title: "Bus Stop Shelter",
    file: "stop.glb",
    location: "Kathmandu, Nepal",
    completion: "March 2025",
    images: [
      "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800&q=80",
      "https://images.unsplash.com/photo-1540541338287-41700207dee6?w=800&q=80",
    ],
    description: "A modern bus stop shelter with integrated solar lighting, digital information display, and seating. Part of the city's public transport infrastructure upgrade.",
    materials: [
      { name: "Weathering Steel", desc: "Corten steel panels for maintenance-free exterior" },
      { name: "Tempered Glass", desc: "6mm toughened glass for windbreaks" },
      { name: "Solar PV Panels", desc: "250W monocrystalline panels on canopy roof" },
      { name: "LED Display", desc: "Weatherproof digital information screen" },
      { name: "Recycled Plastic Benches", desc: "100% recycled plastic seating modules" },
    ],
    costEstimation: [
      { item: "Foundation Work", amount: "NPR 1,50,000" },
      { item: "Steel Structure & Canopy", amount: "NPR 4,00,000" },
      { item: "Glass & Enclosure", amount: "NPR 1,80,000" },
      { item: "Solar & Lighting", amount: "NPR 2,50,000" },
      { item: "Digital Display System", amount: "NPR 3,00,000" },
      { item: "Seating & Accessories", amount: "NPR 1,20,000" },
    ],
    specs: [
      { label: "Covered Area", value: "18 sq.m" },
      { label: "Capacity", value: "15 people" },
      { label: "Solar Capacity", value: "500W" },
      { label: "Lighting", value: "LED + motion sensor" },
      { label: "Display", value: "32\" LCD info screen" },
    ],
  },
  {
    slug: "sunrise-residential-complex",
    title: "Sunrise Residential Complex",
    file: "house.glb",
    location: "Lalitpur, Nepal",
    completion: "December 2025",
    images: [
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&q=80",
      "https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=800&q=80",
    ],
    description: "A modern residential complex featuring 24 apartments across four wings, with a central garden courtyard, children's play area, and underground parking.",
    materials: [
      { name: "Reinforced Concrete Frame", desc: "Earthquake-resistant design per NBC 105" },
      { name: "Fly-ash Bricks", desc: "Eco-friendly bricks for partition walls" },
      { name: "Vitrified Tiles", desc: "Anti-skid flooring in common areas" },
      { name: "Aluminium Windows", desc: "Powder-coated aluminium sliding windows" },
      { name: "Solar Water Heaters", desc: "200L capacity for each apartment" },
    ],
    costEstimation: [
      { item: "Land & Development", amount: "NPR 2,50,00,000" },
      { item: "Structure & Foundation", amount: "NPR 4,80,00,000" },
      { item: "Finishes & Flooring", amount: "NPR 1,20,00,000" },
      { item: "Plumbing & Electrical", amount: "NPR 85,00,000" },
      { item: "Landscaping & Common Areas", amount: "NPR 35,00,000" },
      { item: "Labour & Overhead", amount: "NPR 1,50,00,000" },
    ],
    specs: [
      { label: "Total Units", value: "24" },
      { label: "Floors", value: "G+4" },
      { label: "Apartment Size", value: "1,200 - 1,800 sq.ft" },
      { label: "Parking", value: "28 cars" },
      { label: "Land Area", value: "0.8 acres" },
    ],
  },
  {
    slug: "green-valley-resort",
    title: "Green Valley Eco Resort",
    file: "sand.glb",
    location: "Pokhara, Nepal",
    completion: "October 2024",
    images: [
      "https://images.unsplash.com/photo-1540541338287-41700207dee6?w=800&q=80",
      "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&q=80",
    ],
    description: "An eco-friendly resort with 15 villas nestled in the Pokhara valley, designed with local materials and sustainable construction practices.",
    materials: [
      { name: "Local Stone", desc: "River stone masonry for retaining walls" },
      { name: "Bamboo", desc: "Treated bamboo for pergolas and ceilings" },
      { name: "Clay Roof Tiles", desc: "Handmade local clay tiles" },
      { name: "Recycled Timber", desc: "Sal wood furniture from reclaimed sources" },
    ],
    costEstimation: [
      { item: "Land & Site Prep", amount: "NPR 1,80,00,000" },
      { item: "Villa Construction", amount: "NPR 3,50,00,000" },
      { item: "Common Areas & Pool", amount: "NPR 1,20,00,000" },
      { item: "Landscaping", amount: "NPR 45,00,000" },
      { item: "Interior Fit-Out", amount: "NPR 80,00,000" },
    ],
    specs: [
      { label: "Villas", value: "15" },
      { label: "Land Area", value: "3.2 acres" },
      { label: "Room Capacity", value: "60 guests" },
      { label: "Amenities", value: "Pool, Spa, Restaurant" },
      { label: "Energy", value: "100% solar" },
    ],
  },
  {
    slug: "durbar-square-heritage-inn",
    title: "Durbar Square Heritage Inn",
    file: "stop.glb",
    location: "Bhaktapur, Nepal",
    completion: "August 2024",
    images: [
      "https://images.unsplash.com/photo-1511818966892-d7d671e672a2?w=800&q=80",
      "https://images.unsplash.com/photo-1487958449943-2429e8be8625?w=800&q=80",
    ],
    description: "Restoration and conversion of a traditional Newari townhouse into a boutique heritage inn, preserving original brickwork and timber carvings.",
    materials: [
      { name: "Traditional Bricks", desc: "Handmade Nepali bricks (ma apa)" },
      { name: "Sal Timber", desc: "Restored original timber beams and columns" },
      { name: "Lime Mortar", desc: "Traditional lime-based mortar for masonry" },
      { name: "Terracotta Flooring", desc: "Handmade terracotta tiles throughout" },
    ],
    costEstimation: [
      { item: "Structural Restoration", amount: "NPR 85,00,000" },
      { item: "Interior Renovation", amount: "NPR 55,00,000" },
      { item: "MEP Systems", amount: "NPR 25,00,000" },
      { item: "Furniture & Decor", amount: "NPR 30,00,000" },
    ],
    specs: [
      { label: "Rooms", value: "8" },
      { label: "Floors", value: "4" },
      { label: "Building Age", value: "120+ years" },
      { label: "Style", value: "Traditional Newari" },
    ],
  },
  {
    slug: "himalayan-heights-tower",
    title: "Himalayan Heights Tower",
    file: "folding.glb",
    location: "Kathmandu, Nepal",
    completion: "June 2026",
    images: [
      "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800&q=80",
      "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800&q=80",
    ],
    description: "A 7-storey commercial tower with retail spaces, corporate offices, and a rooftop restaurant offering panoramic Himalayan views.",
    materials: [
      { name: "Glass Curtain Wall", desc: "Double-glazed unitised curtain wall system" },
      { name: "Structural Steel", desc: "ISMB 500 columns for seismic resilience" },
      { name: "Aluminium Composite Panels", desc: "ACP cladding for facade accents" },
      { name: "Elevator System", desc: "2x 13-passenger elevators with destination dispatch" },
    ],
    costEstimation: [
      { item: "Foundation & Structure", amount: "NPR 5,20,00,000" },
      { item: "Facade & Glazing", amount: "NPR 2,80,00,000" },
      { item: "MEP & Fire Safety", amount: "NPR 1,50,00,000" },
      { item: "Interior Fit-Out", amount: "NPR 2,00,00,000" },
      { item: "Elevators & Equipment", amount: "NPR 1,20,00,000" },
    ],
    specs: [
      { label: "Height", value: "28 m" },
      { label: "Floors", value: "G+7" },
      { label: "Total Area", value: "32,000 sq.ft" },
      { label: "Seismic Zone", value: "Zone V compliant" },
      { label: "Parking", value: "40 cars" },
    ],
  },
  {
    slug: "riverside-township",
    title: "Riverside Township",
    file: "sand.glb",
    location: "Chitwan, Nepal",
    completion: "December 2026",
    images: [
      "https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=800&q=80",
      "https://images.unsplash.com/photo-1600573472591-ee6b68d14c68?w=800&q=80",
    ],
    description: "A master-planned riverfront township with 50 residential plots, community amenities, and a riverside promenade.",
    materials: [
      { name: "Concrete Pavers", desc: "Permeable interlocking pavers for walkways" },
      { name: "Stone Curbing", desc: "Local granite for road edges and landscaping" },
      { name: "Steel Street Furniture", desc: "Galvanised steel benches, bins, and lighting poles" },
    ],
    costEstimation: [
      { item: "Land Development", amount: "NPR 3,00,00,000" },
      { item: "Infrastructure & Roads", amount: "NPR 2,50,00,000" },
      { item: "Utilities & Drainage", amount: "NPR 1,20,00,000" },
      { item: "Landscaping & Promenade", amount: "NPR 80,00,000" },
    ],
    specs: [
      { label: "Plots", value: "50" },
      { label: "Plot Sizes", value: "300 - 600 sq.m" },
      { label: "Land Area", value: "10 acres" },
      { label: "Amenities", value: "Park, Community Hall, Walkway" },
    ],
  },
  {
    slug: "mountain-view-residency",
    title: "Mountain View Residency",
    file: "house.glb",
    location: "Dhulikhel, Nepal",
    completion: "March 2025",
    images: [
      "https://images.unsplash.com/photo-1600573472591-ee6b68d14c68?w=800&q=80",
      "https://images.unsplash.com/photo-1600585153490-76fb20a32601?w=800&q=80",
    ],
    description: "A premium residential complex with 12 luxury apartments offering unobstructed Himalayan views from every unit.",
    materials: [
      { name: "Reinforced Concrete", desc: "Grade M30 for all structural elements" },
      { name: "Stone Cladding", desc: "Local schist stone for exterior accents" },
      { name: "Hardwood Flooring", desc: "Burma teak engineered flooring" },
      { name: "Double-Glazed Windows", desc: "Thermally broken aluminium frames" },
    ],
    costEstimation: [
      { item: "Structure & Foundation", amount: "NPR 3,20,00,000" },
      { item: "Finishes & Flooring", amount: "NPR 1,80,00,000" },
      { item: "Plumbing & Electrical", amount: "NPR 70,00,000" },
      { item: "Landscaping & Parking", amount: "NPR 45,00,000" },
    ],
    specs: [
      { label: "Units", value: "12" },
      { label: "Floors", value: "G+3" },
      { label: "Unit Size", value: "1,500 - 2,200 sq.ft" },
      { label: "Parking", value: "2 per unit" },
    ],
  },
  {
    slug: "lakeside-boutique-hotel",
    title: "Lakeside Boutique Hotel",
    file: "folding.glb",
    location: "Pokhara, Nepal",
    completion: "September 2025",
    images: [
      "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&q=80",
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&q=80",
    ],
    description: "A boutique 18-room hotel on Pokhara's lakeside strip, featuring a rooftop infinity pool and panoramic views of Fewa Lake.",
    materials: [
      { name: "RCC Frame", desc: "Earthquake-resistant concrete frame" },
      { name: "Local Stone", desc: "Stone masonry accent walls" },
      { name: "Glass Balustrades", desc: "Tempered glass for balcony railings" },
      { name: "Porcelain Tiles", desc: "Large-format tiles for public areas" },
    ],
    costEstimation: [
      { item: "Construction", amount: "NPR 4,50,00,000" },
      { item: "Interior Design", amount: "NPR 1,20,00,000" },
      { item: "Pool & Rooftop", amount: "NPR 60,00,000" },
      { item: "FF&E", amount: "NPR 80,00,000" },
    ],
    specs: [
      { label: "Rooms", value: "18" },
      { label: "Floors", value: "G+4" },
      { label: "Restaurants", value: "2" },
      { label: "Pool", value: "Rooftop infinity" },
    ],
  },
  {
    slug: "garden-city-township",
    title: "Garden City Township",
    file: "sand.glb",
    location: "Chitwan, Nepal",
    completion: "December 2026",
    images: [
      "https://images.unsplash.com/photo-1486325212027-8081e485255e?w=800&q=80",
      "https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=800&q=80",
    ],
    description: "A sustainable township with integrated green spaces, community farming plots, and solar-powered infrastructure for 80+ families.",
    materials: [
      { name: "Compressed Earth Blocks", desc: "Stabilised CEB for all residential walls" },
      { name: "Bamboo Roofing", desc: "Engineered bamboo trusses for community hall" },
      { name: "Solar PV", desc: "200 kW community solar installation" },
      { name: "Rainwater Harvesting", desc: "Central 50,000L collection system" },
    ],
    costEstimation: [
      { item: "Land & Planning", amount: "NPR 5,00,00,000" },
      { item: "Infrastructure & Roads", amount: "NPR 3,50,00,000" },
      { item: "Community Buildings", amount: "NPR 1,80,00,000" },
      { item: "Solar & Water Systems", amount: "NPR 1,00,00,000" },
    ],
    specs: [
      { label: "Homes", value: "80+" },
      { label: "Land Area", value: "25 acres" },
      { label: "Green Space", value: "40%" },
      { label: "Solar Capacity", value: "200 kW" },
    ],
  },
];

export function getProjectBySlug(slug: string) {
  return projects.find((p) => p.slug === slug) ?? null;
}
